version: '3.9'

services:
  backend:
    container_name: backend
    build: ./backend
    command: /scripts/start_dev.sh
    depends_on:
      - db
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - django-static:/app/static
    env_file:
      - ./.env
    environment:
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - CORS_ALLOWED_ORIGINS=${DJANGO_CORS_ALLOWED_ORIGINS}
      - DEBUG=1
    networks:
      - main

  db:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data/
    networks:
      - main

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    networks:
      - main
    environment:
      - NODE_ENV=development

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/dev/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - main
    volumes:
      - ./nginx/dev/dev.conf:/etc/nginx/nginx.conf:ro
      - django-static:/usr/src/app/static

volumes:
  dbdata:
  django-static:

networks:
  main:
    driver: bridge